In [6]:
!pip install fastdtw

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for fastdtw: filename=fastdtw-0.3.4-cp310-cp310-linux_x86_64.whl size=512710 sha256=537f2751e5679a4c582e4902edf2a9785a02b4885abf9915c3f177d6b3274c77
  Stored in directory: /root/.cache/pip/wheels/73/c8/f7/c25448dab74c3acf4848bc25d513c736bb93910277e1528ef4
Successfully built fastdtw


In [7]:
from fastdtw import fastdtw

In [16]:
import numpy as np
from scipy.spatial.distance import cdist

def calculate_distance_matrix(data, metric='euclidean', normalize=True):
    """
    Вычисляет матрицу расстояний между временными рядами, представленными в виде матрицы.

    Args:
        data (np.ndarray): Матрица временных рядов, где каждая строка представляет временной ряд.
        metric (str): Метрика расстояния, например, 'euclidean' (по умолчанию) или 'dtw'.
        normalize (bool): Если True, нормализует матрицу расстояний.

    Returns:
        np.ndarray: Матрица расстояний между временными рядами.
    """
    n = data.shape[0]  # Количество временных рядов

    if metric == 'euclidean':
        # Используем евклидово расстояние
        distance_matrix = cdist(data, data, metric='euclidean')
    elif metric == 'dtw':
        # Используем расстояние динамической трансформации (DTW)


        distance_matrix = np.zeros((n, n))
        for i in range(n):
            for j in range(i, n):
                distance, _ = fastdtw(data[i], data[j])
                distance_matrix[i, j] = distance
                distance_matrix[j, i] = distance  # Матрица симметрична


    if normalize:
        # Нормализация матрицы расстояний
        max_distance = np.max(distance_matrix)
        min_distance = np.min(distance_matrix)
        distance_matrix = (distance_matrix - min_distance) / (max_distance - min_distance)

    return distance_matrix

# Пример временных рядов, представленных в виде матрицы
data = np.array([[1, 3, 5],
                 [0, 2, 4],
                 [2, 3, 6]])

# Вычисление матрицы расстояний с использованием евклидова расстояния
distance_matrix = calculate_distance_matrix(data, metric='euclidean')

# Вывод матрицы расстояний
print("Distance Matrix (Euclidean):")
print(distance_matrix)

# Вычисление матрицы расстояний с использованием DTW
distance_matrix_dtw = calculate_distance_matrix(data, metric='dtw')

# Вывод матрицы расстояний DTW
print("\nDistance Matrix (DTW):")
print(distance_matrix_dtw)

Distance Matrix (Euclidean):
[[0.         0.57735027 0.47140452]
 [0.57735027 0.         1.        ]
 [0.47140452 1.         0.        ]]

Distance Matrix (DTW):
[[0.  0.6 0.4]
 [0.6 0.  1. ]
 [0.4 1.  0. ]]


In [19]:
import numpy as np
from scipy.spatial.distance import cdist

def calculate_distance_matrix(data, metric='euclidean', normalize=True):

    n = data.shape[0]  # Количество временных рядов

    if metric == 'euclidean':
        # Используем евклидово расстояние
        distance_matrix = cdist(data, data, metric='euclidean')
    elif metric == 'dtw':
        distance_matrix = np.zeros((n, n))
        for i in range(n):
            for j in range(i, n):
                distance, _ = fastdtw(data[i], data[j])
                distance_matrix[i, j] = distance
                distance_matrix[j, i] = distance  # Матрица симметрична

    if normalize:
        # Нормализация матрицы расстояний
        max_distance = np.max(distance_matrix)
        min_distance = np.min(distance_matrix)
        distance_matrix = (distance_matrix - min_distance) / (max_distance - min_distance)

    return distance_matrix

# Пример временных рядов, представленных в виде матрицы
data = np.array([[81, 15, 59, 15, 69],
       [87,  9, 56, 15, 41],
       [61, 16, 14, 13, 45],
       [33, 80, 81, 10, 54],
       [32, 70, 96, 42, 82]])
# Вычисление матрицы расстояний с использованием евклидова расстояния
distance_matrix = calculate_distance_matrix(data, metric='euclidean')

# Вывод матрицы расстояний
print("Distance Matrix (Euclidean):")
print(distance_matrix)

# Вычисление матрицы расстояний с использованием DTW
distance_matrix_dtw = calculate_distance_matrix(data, metric='dtw')

# Вывод матрицы расстояний DTW
print("\nDistance Matrix (DTW):")
print(distance_matrix_dtw)

Distance Matrix (Euclidean):
[[0.         0.2610719  0.48668344 0.75650203 0.77857409]
 [0.2610719  0.         0.44463373 0.83157301 0.92061379]
 [0.48668344 0.44463373 0.         0.86332574 1.        ]
 [0.75650203 0.83157301 0.86332574 0.         0.41006177]
 [0.77857409 0.92061379 1.         0.41006177 0.        ]]

Distance Matrix (DTW):
[[0.         0.21938776 0.46428571 0.57653061 0.78571429]
 [0.21938776 0.         0.40816327 0.62244898 1.        ]
 [0.46428571 0.40816327 0.         0.45408163 0.98469388]
 [0.57653061 0.62244898 0.45408163 0.         0.43877551]
 [0.78571429 1.         0.98469388 0.43877551 0.        ]]
